LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

OLED_ENABLE = yes
ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no

TAP_DANCE_ENABLE = yes

# BOOTMAGIC_ENABLE = yes
# AUTO_SHIFT_ENABLE = no
# CAPS_WORD_ENABLE = yes

# VIA_ENABLE = no

# COMBO_ENABLE = yes
# VPATH += keyboards/gboards
# TAP_DANCE_ENABLE = yes

# RGBLIGHT_ENABLE=yes
# VELOCIKEY_ENABLE=yes

