#pragma once

#define TAPPING_TERM 180
#define CHORDAL_HOLD
#undef PERMISSIVE_HOLD
#define FLOW_TAP_TERM 150
#define RETRO_SHIFT 500
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define TAPPING_TOGGLE 2
#define SELECT_WORD_OS_MAC

#define LED_UART_BAUD_RATE 57600
