LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = no

BOOTMAGIC_ENABLE = yes
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = yes

COMBO_ENABLE = yes
VPATH += keyboards/gboards
TAP_DANCE_ENABLE = no

RGB_MATRIX_ENABLE = yes
