LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = yes
AUTOCORRECT_ENABLE = yes

COMBO_ENABLE = no
TAP_DANCE_ENABLE = yes

LAYER_LOCK_ENABLE = yes
REPEAT_KEY_ENABLE = yes

RGB_MATRIX_ENABLE = yes

SRC += leader_fns.c
SRC += magic.c
