#pragma once

#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_VAL 128

#define TAPPING_TERM 200
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define RETRO_SHIFT 500
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define TAPPING_TOGGLE 2
#define SELECT_WORD_OS_MAC
