LTO_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = no

BOOTMAGIC_ENABLE = yes
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = yes

VIA_ENABLE = no

COMBO_ENABLE = yes
VPATH += keyboards/gboards
TAP_DANCE_ENABLE = yes

RGBLIGHT_ENABLE=yes
VELOCIKEY_ENABLE=yes

REPEAT_KEY_ENABLE = yes
LAYER_LOCK_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
UNICODEMAP_ENABLE = yes

CONVERT_TO = rp2040_ce
