#define TAPPING_TERM 250
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

#define QUICK_TAP_TERM_PER_KEY

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Gee9j/wOblqo"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define SELECT_WORD_OS_MAC

#define RGB_MATRIX_KEYPRESSES // for PaletteFx Reactive

#define PALETTEFX_REACTIVE_ENABLE
#define PALETTEFX_ENABLE_ALL_PALETTES
