#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM_PER_KEY

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Gee9j/wOblqo"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60
